/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

#include <iostream>
#include <vector>

using namespace std;

int main(){
    int a = 1;
    int b = 1;
    int even_sum=0;

    cout << "The Fibonacci sequence for values that do not exceed 4 million: " << '\n';
    while (a <= 4000000){
        int c = b;
        cout << b <<'\n';
        if (b%2==0)
            even_sum=even_sum+b;
            
        b = b + a;
        a = c;
    }
    
    cout << '\n' << "The sum of the even-valued terms is: " << even_sum << '\n';
    return 0;
}
